const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const FETCH_BRANCHES = "FETCH_BRANCHES";
const DESCREASE_VIEWER = "DESCREASE_VIEWER";

export default {
    FETCH_PRODUCTS,
    FETCH_CATEGORIES,
    FETCH_BRANCHES,
    DESCREASE_VIEWER
};
